services:
  tracker:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: application
    entrypoint: ["poetry", "run", "python", "src/tracking.py"]
    volumes:
      - ../src:/app/src
      - ../data/tracking.yml:/app/data/tracking.yml
